"""empty message

Revision ID: 298958991582
Revises: b20a2f7424eb
Create Date: 2017-01-23 21:33:54.251594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298958991582'
down_revision = 'b20a2f7424eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('article', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['author'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
